name: opennebula
description: OpenNebula cloud computing platform
version: 2.1.0
appVersion: 5.12.0.4-1
icon: https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/OpenNebula-logo.svg/330px-OpenNebula-logo.svg.png
keywords:
  - opennebula
  - virtualization
home: https://github.com/kvaps/kube-opennebula
sources:
  - https://github.com/kvaps/kube-opennebula
maintainers:
  - name: kvaps
    email: kvapss@gmail.com
