{{- if .Values.gate.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-gate
  labels:
    app: {{ $fullName }}-gate
    {{- if .Values.gate.labels }}
    {{- toYaml .Values.gate.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.gate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.gate.replicas }}
  selector:
    matchLabels:
      app: {{ $fullName }}-gate
  template:
    metadata:
      labels:
        app: {{ $fullName }}-gate
        {{- with .Values.gate.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/gate-configmap.yaml") . | sha256sum }}
        {{- with .Values.gate.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: onegate
        image: {{ .Values.gate.image.repository }}:{{ .Values.gate.image.tag }}
        imagePullPolicy: {{ .Values.gate.image.pullPolicy }}
        command: [ "/usr/bin/ruby", "/usr/lib/one/onegate/onegate-server.rb" ]
        ports:
        - name: http
          containerPort: {{ .Values.gate.port }}
        {{- with .Values.gate.extraEnv }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        {{- with .Values.timezone }}
        - name: timezone
          mountPath: /etc/localtime
          readOnly: true
        {{- end }}
        - mountPath: /etc/one/onegate-server.conf
          name: config
          subPath: onegate-server.conf
        - mountPath: /var/lib/one/.one/onegate_auth
          name: one-keys
          subPath: onegate_auth
        {{- with .Values.gate.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.gate.sidecars }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if or .Values.gate.affinity .Values.gate.podAntiAffinity }}
      affinity:
        {{- with .Values.gate.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if eq .Values.gate.podAntiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "{{ .Values.gate.podAntiAffinityTopologyKey }}"
              labelSelector:
                matchLabels:
                  app: {{ $fullName }}-gate
        {{- else if eq .Values.gate.podAntiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "{{ .Values.gate.podAntiAffinityTopologyKey }}"
                labelSelector:
                  matchLabels:
                    app: {{ $fullName }}-gate
        {{- end }}
      {{- end }}
      {{- with .Values.gate.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.gate.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gate.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      securityContext:
        fsGroup: 9869
        runAsUser: 9869
      volumes:
      {{- with .Values.timezone }}
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/{{ . }}
          type: File
      {{- end }}
      - name: config
        configMap:
          name: {{ $fullName }}-gate
      - name: one-keys
        secret:
          secretName: {{ $fullName }}-one-keys
      {{- with .Values.gate.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
