{{- if and .Values.novnc.enabled .Values.novnc.ingress.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
{{- $servicePort := .Values.novnc.service.port -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-novnc
  labels:
    app: {{ $fullName }}-novnc
    {{- if .Values.novnc.ingress.labels }}
    {{- toYaml .Values.novnc.ingress.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.novnc.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.novnc.ingress.ingressClassName }}
  rules:
  {{- range .Values.novnc.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /websockify
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-novnc
            port:
              number: {{ $servicePort }}
  {{- end }}
  {{- if .Values.novnc.ingress.tls }}
  tls:
    {{- toYaml .Values.novnc.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
