{{- if .Values.oned.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-oned
  labels:
    app: {{ $fullName }}-oned
data:
  oned.conf: |+
    {{- $mergedConfig := include "opennebula.config" (mergeOverwrite (fromYaml (tpl (.Files.Get "config/oned.conf") .)) .Values.oned.configOverrides) -}}
    {{- $mergedConfig | nindent 4 }}
    {{- $appendConfig := include "opennebula.config" .Values.oned.configAppends | nindent 4 -}}
    {{- $appendConfig }}
  monitord.conf: |+
    {{- $mergedConfig := include "opennebula.config" (mergeOverwrite (fromYaml (tpl (.Files.Get "config/monitord.conf") .)) .Values.oned.monitord.configOverrides) -}}
    {{- $mergedConfig | nindent 4 }}
    {{- $appendConfig := include "opennebula.config" .Values.oned.monitord.configAppends | nindent 4 -}}
    {{- $appendConfig }}
{{- end }}
