{{- if .Values.oned.enabled }}
{{- $fullName := include "opennebula.fullname" . -}}
{{- $servicePort := .Values.oned.service.port -}}
{{- $hmSubscriberServicePort := .Values.oned.one_hm.service.subscriberPort -}}
{{- $hmReplierServicePort := .Values.oned.one_hm.service.replierPort -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned-servers
  labels:
    app: {{ $fullName }}-oned
    {{- if .Values.oned.service.labels }}
    {{- toYaml .Values.oned.service.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.oned.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: http
    port: {{ $servicePort }}
  - name: hm-subscriber
    port: {{ $hmSubscriberServicePort }}
  - name: hm-replier
    port: {{ $hmReplierServicePort }}
  selector:
    app: {{ $fullName }}-oned
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned-headless
  labels:
    app: {{ $fullName }}-oned
    {{- if .Values.oned.service.labels }}
    {{- toYaml .Values.oned.service.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.oned.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
  - name: http
    port: {{ $servicePort }}
  - name: hm-subscriber
    port: {{ $hmSubscriberServicePort }}
  - name: hm-replier
    port: {{ $hmReplierServicePort }}
  selector:
    app: {{ $fullName }}-oned
    role: leader
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned
  labels:
    app: {{ $fullName }}-oned
    {{- if .Values.oned.service.labels }}
    {{- toYaml .Values.oned.service.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.oned.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: {{ $servicePort }}
  - name: hm-subscriber
    port: {{ $hmSubscriberServicePort }}
  - name: hm-replier
    port: {{ $hmReplierServicePort }}
  selector:
    app: {{ $fullName }}-oned
    role: leader
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-oned-monitord
  labels:
    app: {{ $fullName }}-oned
    {{- if .Values.oned.monitord.service.labels }}
    {{- toYaml .Values.oned.monitord.service.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.oned.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: monitord
    port: {{ .Values.oned.monitord.port }}
    nodePort: {{ .Values.oned.monitord.service.nodePort }}
  selector:
    app: {{ $fullName }}-oned
  type: NodePort
{{- end }}
